### ISSUE TITLE
Parsing of heredoc identifier broken?

### ISSUE THREAD

**Issue by rchl** [SublimeText/Terraform#43]
This heredoc template expression breaks parsing:

```
<<__EOF__
aaa
__EOF__
```

It looks like because the identifier used here (`__EOF__`) starts with an underscore and that is deemed invalid.

I've tried to understand what characters are allowed in identifiers but going down the rabbit hole almost exploded my brain when trying to understand the unicode spec stuff.

HCL syntax spec says [1]:

> The heredoc template expression type is introduced by either << or <<-, followed by an identifier.

and "identifier" is defined as [2]:

> Identifiers name entities such as blocks, attributes and expression variables. Identifiers are interpreted as per [UAX #31](http://unicode.org/reports/tr31/) Section 2.
> Identifier = ID_Start (ID_Continue | '-')*;

Where the UAX link points to a spec where I completely lost comprehension.

So the question is, can the identifier start with an underscore? Terraform actually works just fine with it so I guess yes.

[1] https://github.com/hashicorp/hcl/blob/hcl2/hclsyntax/spec.md#template-expressions
[2] https://github.com/hashicorp/hcl/blob/hcl2/hclsyntax/spec.md#identifiers

**Comment by FichteFoll** [comment]
Indeed, it turns out that, [according to the Unicode spec](http://unicode.org/reports/tr31/#Table_Lexical_Classes_for_Identifiers), an underscore character `_` (U+005F) is *not* an allowed ID_Start character. It is part of the [Pc category](https://www.compart.com/en/unicode/category/Pc), which is part of ID_Continue, but not ID_Start. 

That said, it appears that an underscore is indeed parsed without complained, so I'm adding it as an exception and will create a ticket mentioning this on their repo.
